### ISSUE TITLE
Cooling time calculation prefactor correction

### ISSUE THREAD

**Issue by dutta-alankar** [dfielding14/MultiphaseGalacticWind#2]
Line 111 in `MultiphaseGalacticWind.py`
`return 1.5 * (muH/mu)**2 * kb * T / ( nH_actual * Lambda_z0((np.log10(nH),np.log10(T), metallicity)))`
needs to be changed to
`return 1.5 * (muH/mu) * kb * T / ( nH_actual * Lambda_z0((np.log10(nH),np.log10(T), metallicity)))`
Gas adiabatic index **gamma** is hard coded!

**Comment by dfielding14** [comment]
Good catch!
